cobbler:
  build: cobbler/ 
  expose:
    - 8000
    - 25151
    - 69/udp
    - 80
    - 443
  volumes:
     - ./etc/cobbler/settings:/etc/cobbler/settings 
     - ./etc/cobbler/dhcp.template:/etc/cobbler/dhcp.template 
     - ./var/www/cobbler/images:/var/www/cobbler/images \
     - ./var/www/cobbler/ks_mirror:/var/www/cobbler/ks_mirror 
     - ./var/www/cobbler/links:/var/www/cobbler/links 
     - ./var/lib/cobbler/config:/var/lib/cobbler/config 
  links:
    - dhcpd

dhcpd:
  build: dhcpd/
  entrypoint: /entrypoint.sh  
  volumes:
    - /etc/dhcpd/:/data
  expose:
    - 67
    - 67/udp
    - 547
    - 547/udp
    - 647
    - 647/udp
    - 847
    - 847/udp


